kitchen:
  type: tasmota-shelly-2.5
  prefix: kitchen
  entities:
    kitchen_lamp: 1
    coffee_machine: 2
living_room:
  type: tasmota-sonoff
  prefix: living_room
  entities:
    living_room_lamp: 1
    tv: 2
